"""create_schema

Revision ID: 7b57ba2d1df5
Revises: 
Create Date: 2026-04-19 21:18:00.513310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b57ba2d1df5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('price_per_character', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('allow_negative_balance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_ledger_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_ledger_entries_user_id'), ['user_id'], unique=False)

    op.create_table('ml_prediction_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('is_toxic', sa.Boolean(), nullable=True),
    sa.Column('toxicity_probability', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('toxicity_breakdown', sa.JSON(), nullable=True),
    sa.Column('charged_tokens', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_prediction_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_prediction_tasks_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_prediction_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('user_balances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_count', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_type', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_attempts_left', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_type', 'identifier', name='uq_user_identities_type_identifier')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_identity_type'), ['identity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)

    op.create_table('history_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ml_model_id', sa.Uuid(), nullable=True),
    sa.Column('ml_task_id', sa.Uuid(), nullable=True),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('tokens_charged', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ml_task_id'], ['ml_prediction_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_records_ml_model_id'), ['ml_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_records_ml_task_id'), ['ml_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_records_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_toxic', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_history_id'), ['history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_history_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_history_records_ml_task_id'))
        batch_op.drop_index(batch_op.f('ix_history_records_ml_model_id'))

    op.drop_table('history_records')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_identities_identity_type'))
        batch_op.drop_index(batch_op.f('ix_user_identities_identifier'))

    op.drop_table('user_identities')
    op.drop_table('user_balances')
    with op.batch_alter_table('ml_prediction_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_prediction_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_prediction_tasks_model_id'))

    op.drop_table('ml_prediction_tasks')
    with op.batch_alter_table('balance_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_ledger_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_ledger_entries_task_id'))

    op.drop_table('balance_ledger_entries')
    op.drop_table('users')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_slug'))

    op.drop_table('ml_models')
    # ### end Alembic commands ###
